name = "BcdiSimulate"
uuid = "b133d2d9-b23b-44ee-be6b-5f897f6a3084"
authors = ["Jason Meziere"]
version = "0.0.1"

[deps]
BcdiCore = "72eb6a3e-ca63-4742-b260-85b05ca6d9e4"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LAMMPS = "ee2e13b9-eee9-4449-aafa-cfa6a2dbe14d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.10"
BcdiCore = "0.0.1"
CUDA = "5.4.3"
Distributions = "0.25.110"
LAMMPS = "0.7.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
